# Generated by Django 3.0.3 on 2020-02-19 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0002_wish_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='description',
        ),
        migrations.AddField(
            model_name='wish',
            name='Url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
