# Generated by Django 3.0.3 on 2020-02-19 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishapp', '0003_auto_20200219_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='Url',
        ),
        migrations.AddField(
            model_name='wish',
            name='url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
