# Generated by Django 3.0.3 on 2020-02-19 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wishapp', '0004_auto_20200219_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wish',
            name='user',
        ),
        migrations.AddField(
            model_name='wish',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
